---
- hosts: localhost
  vars_files:
    - ['settings.yml', 'defaults/settings.yml.default']
  roles:
    - { role: user, tags: ['core', 'devbox', 'user'] }
    - { role: common, tags: ['core', 'devbox'] }
    - { role: docker, tags: ['core', 'devbox'] }
    - { role: liquibase, tags: ['devbox','liquibase'] }
    - { role: oracledb, tags: ['devbox','oracledb'] }
    - { role: dbdeploy, tags: ['dbdeploy'] }