---
- hosts: localhost
  vars_files:
    - ['settings.yml', 'defaults/settings.yml.default']
  tasks:
    - debug: msg={{ oracledb_password }}
      tags: ['testing']
  roles:
    - { role: user, tags: ['preinstall', 'user'] }
    - { role: common, tags: ['core', 'devbox', 'preinstall', 'common'] }
    - { role: docker, tags: ['core', 'devbox'] }
    - { role: oracledb, tags: ['devbox','oracledb'] }
    - { role: liquibase, tags: ['devbox','liquibase'] }
    - { role: dbdeploy, tags: ['dbdeploy'] }