---
- name: Create common groups
  group: "name={{ item }} state=present"
  with_items:
    - docker
    - "{{ user }}"

- name: "Create user '{{ user }}'"
  user:
    name: "{{ user }}"
    groups: "{{ user }},wheel,docker"
    append: yes
  register: user_info

- debug: msg="Please restart sessions for group additions to take effect using 'logoout'"