---
- name: clean up docker build files
  file:
    path: "{{ role_path }}/repo"
    state: absent

- name: "create liquibase changelog directory"
  file: "path={{ item }} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - "/opt/devbox/liquibase"
    - "/opt/devbox/liquibase/changelog"
    - "{{ role_path }}/repo"

- name: retrieve from github
  git:
    repo: https://github.com/whiskaz/docker-liquibase.git
    dest: "{{ role_path }}/repo"

- name: docker build
  docker_image:
    name: liquibase
    tag: 3.5.5
    path: "{{ role_path }}/repo"
    buildargs:
      VERSION: 3.5.5

- name: "stop and remove any existing container"
  docker_container:
    name: liquibase
    state: absent

- name: create container
  docker_container:
    name: liquibase
    image: liquibase:3.5.5
    volumes:
      - /opt/devbox/liquibase/changelog:/liquibase/changelog
    restart_policy: always
    interactive: yes
    tty: yes
    networks:
      - name: "devbox"