ALTER SESSION SET CONTAINER = :oracledb_pid;

--Create user
CREATE USER :oracledb_uid
  IDENTIFIED BY #password#
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

--Provide roles
GRANT CONNECT,
DATAPUMP_EXP_FULL_DATABASE,
DATAPUMP_IMP_FULL_DATABASE,
DBA,
EXECUTE_CATALOG_ROLE,
GATHER_SYSTEM_STATISTICS,
RESOURCE
TO DEVBOX CONTAINER=CURRENT;

ALTER USER DEVBOX DEFAULT ROLE CONNECT, RESOURCE;

GRANT COMMENT ANY TABLE TO DEVBOX;
GRANT CREATE ANY INDEX TO DEVBOX;
GRANT CREATE ANY SEQUENCE TO DEVBOX;
GRANT CREATE ANY TABLE TO DEVBOX;
GRANT CREATE ANY TRIGGER TO DEVBOX;
GRANT CREATE ANY TYPE TO DEVBOX;
GRANT CREATE ANY VIEW TO DEVBOX;
GRANT CREATE DATABASE LINK TO DEVBOX;
GRANT CREATE INDEXTYPE TO DEVBOX;
GRANT CREATE JOB TO DEVBOX;
GRANT CREATE MATERIALIZED VIEW TO DEVBOX;
GRANT CREATE PROCEDURE TO DEVBOX;
GRANT CREATE ROLE TO DEVBOX;
GRANT CREATE SEQUENCE TO DEVBOX;
GRANT CREATE SYNONYM TO DEVBOX;
GRANT CREATE TABLE TO DEVBOX;
GRANT CREATE TRIGGER TO DEVBOX;
GRANT CREATE VIEW TO DEVBOX;
GRANT SELECT ANY DICTIONARY TO DEVBOX;
GRANT UNLIMITED TABLESPACE TO DEVBOX CONTAINER=CURRENT;